name: 'Rust Release binary'
description: 'Automate publishing Rust build artifacts for GitHub releases through GitHub Actions'
inputs:
  GITHUB_TOKEN:
    required: true
  EXTRA_FILES:
    description: 'List of extra files to include in build'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
